// 中文本土化翻译数据
// 从小程序迁移，与 canonical.en.json 配合使用

export const zhProducts: Record<string, string> = {
  "SiteHub": "辰汇导航",
  "MornSocial": "辰汇社交",
  "MornGPT": "辰汇GPT",
  "DeepFake": "辰汇创影",
  "MornStudio": "辰汇工作室",
  "SecFile": "辰汇加密",
  "AutoTools": "辰汇自动化",
  "MornJob": "辰汇招聘",
  "MornTopics": "辰汇话题",
  "MornCompare": "辰汇比价",
  "MornCoder": "辰汇编程",
  "MornInterviewer": "辰汇面试"
}

export const zhCategories: Record<string, string> = {
  "Favorites": "收藏",
  "Custom Sites": "自定义网站",
  "All Sites": "全部网站",
  "China": "中国网站",
  "Social Media": "社交",
  "Video & Streaming": "视频",
  "Shopping": "购物",
  "Dev Tools": "开发工具",
  "News & Media": "资讯", 
  "Finance": "金融",
  "Education": "教育",
  "Productivity": "效率",
  "Design": "设计",
  "Gaming": "游戏",
  "Travel": "旅行",
  "Food & Delivery": "美食",
  "Health & Fitness": "健康",
  "Music": "音乐"
}

export const zhSites: Record<string, string> = {
  // 国内网站 - 使用官方中文名
  "Bilibili": "哔哩哔哩",
  "Zhihu": "知乎", 
  "Douban": "豆瓣",
  "Weibo": "微博",
  "Taobao": "淘宝",
  "JD": "京东",
  "Baidu": "百度",
  "WeChat": "微信",
  "QQ": "QQ",
  "NetEase": "网易",
  "Sina": "新浪",
  "Youku": "优酷",
  "iQiyi": "爱奇艺",
  "Tencent Video": "腾讯视频",
  "Douyin": "抖音",
  "Kuaishou": "快手",
  "Xiaohongshu": "小红书", 
  "Tmall": "天猫",
  "Pinduoduo": "拼多多",
  "Meituan": "美团",
  "Eleme": "饿了么",
  "Dianping": "大众点评",
  "Alipay": "支付宝",
  "Didi": "滴滴出行",
  "12306": "12306",
  "Ctrip": "携程",

  // 国际网站 - 优先品牌英文或官方中文名
  "Google": "Google",
  "YouTube": "YouTube", 
  "Facebook": "Facebook",
  "Instagram": "Instagram",
  "Twitter": "Twitter",
  "LinkedIn": "领英",
  "GitHub": "GitHub",
  "Netflix": "Netflix",
  "Amazon": "亚马逊",
  "eBay": "eBay",
  "PayPal": "PayPal", 
  "Stripe": "Stripe",
  "Apple": "Apple",
  "Microsoft": "微软",
  "Notion": "Notion",
  "Figma": "Figma",
  "Slack": "Slack",
  "Zoom": "Zoom",
  "TikTok": "TikTok",
  "Spotify": "Spotify",
  "Pinterest": "Pinterest",
  "Reddit": "Reddit",
  "Discord": "Discord",
  "Telegram": "Telegram",
  "WhatsApp": "WhatsApp",
  "Skype": "Skype",
  "ChatGPT": "ChatGPT",
  "Midjourney": "Midjourney",
  "Canva": "Canva", 
  "Trello": "Trello",
  "Asana": "Asana",
  "Monday": "Monday",
  "Airtable": "Airtable",
  "Dropbox": "Dropbox",
  "Google Drive": "Google 云端硬盘",
  "OneDrive": "OneDrive",
  "Stack Overflow": "Stack Overflow",
  "CodePen": "CodePen",
  "Dribbble": "Dribbble", 
  "Behance": "Behance",
  "Unsplash": "Unsplash",
  "Pexels": "Pexels",
  "Medium": "Medium",
  "Quora": "Quora", 
  "Wikipedia": "维基百科",
  "Khan Academy": "可汗学院",
  "Coursera": "Coursera",
  "Udemy": "Udemy",
  "Airbnb": "爱彼迎",
  "Booking": "Booking",
  "Expedia": "Expedia",
  
  // 更多国内网站翻译
  "VIP.com": "唯品会",
  "Vancl": "凡客诚品",
  "JD Worldwide": "京东全球购",
  "Mango TV": "芒果TV",
  "Sohu Video": "搜狐视频",
  "PPTV": "PPTV",
  "LeTV": "乐视网",
  "AcFun": "AcFun",
  "People's Daily": "人民日报",
  "Xinhua": "新华网",
  "CCTV": "央视网",
  "China Daily": "中国日报",
  "Global Times": "环球时报",
  "WeChat Pay": "微信支付",
  "Alipay Global": "支付宝国际版",
  "UnionPay": "银联",
  "ICBC": "工商银行",
  "CCB": "建设银行",
  "ABC": "农业银行",
  "Koubei": "口碑",
  "Nuomi": "糯米",
  "Dazhong Dianping": "大众点评",
  "Huochepiao": "火车票",
  "XuetangX": "学堂在线",
  "Zhihuishu": "智慧树",
  "iCourse163": "中国大学MOOC",
  "Tencent Classroom": "腾讯课堂",
  "Zhongxue": "中学网",
  "Baidu Maps": "百度地图",
  "Amap": "高德地图",
  "Tencent Maps": "腾讯地图",
  "Sogou": "搜狗",
  "360 Search": "360搜索",
  "Netease Games": "网易游戏",
  "Tencent Games": "腾讯游戏",
  "Perfect World": "完美世界",
  "Shanda": "盛大",
  "Changyou": "畅游",
  "Netease Music": "网易云音乐",
  "QQ Music": "QQ音乐",
  "Kugou": "酷狗音乐",
  "Kuwo": "酷我音乐",
  "Xiami": "虾米音乐",
  "Toutiao": "今日头条",
  "Sohu": "搜狐", 
  "iFeng": "凤凰网",
  "Hupu": "虎扑",
  "Jianshu": "简书",
  "CSDN": "CSDN技术社区",
  "CNBlogs": "博客园",
  "Gitee": "码云",
  "Lagou": "拉勾网",
  "Zhaopin": "智联招聘", 
  "Boss Zhipin": "Boss直聘",
  "Qidian": "起点中文网",
  "Dangdang": "当当网",
  "Suning": "苏宁易购",
  "Gome": "国美",
  "Vipshop": "唯品会",
  "Xiaomi": "小米",
  "Huawei": "华为",
  "OPPO": "OPPO",
  "Vivo": "Vivo",

  // 更多国际网站翻译
  "Shopify": "Shopify",
  "WordPress": "WordPress",
  "Squarespace": "Squarespace", 
  "Wix": "Wix",
  "Mailchimp": "Mailchimp",
  "HubSpot": "HubSpot",
  "Salesforce": "Salesforce",
  "Adobe": "Adobe",
  "Sketch": "Sketch",
  "InVision": "InVision",
  "Framer": "Framer",
  "Miro": "Miro",
  "Confluence": "Confluence",
  "Jira": "Jira",
  "Bitbucket": "Bitbucket",
  "GitLab": "GitLab",
  "Jenkins": "Jenkins",
  "Docker": "Docker",
  "Kubernetes": "Kubernetes",
  "AWS": "AWS",
  "Google Cloud": "Google Cloud",
  "Microsoft Azure": "Microsoft Azure",
  "Vercel": "Vercel",
  "Netlify": "Netlify",
  "Heroku": "Heroku",
  "DigitalOcean": "DigitalOcean",
  "Linode": "Linode",
  "Vultr": "Vultr",
  "Twitch": "Twitch",
  "Vimeo": "Vimeo",
  "Dailymotion": "Dailymotion",
  "SoundCloud": "SoundCloud",
  "Bandcamp": "Bandcamp",
  "Last.fm": "Last.fm",
  "Deezer": "Deezer",
  "Apple Music": "Apple Music",
  "Pandora": "Pandora",
  "Snapchat": "Snapchat",
  "Clubhouse": "Clubhouse",
  "Mastodon": "Mastodon",
  "Signal": "Signal",
  "Viber": "Viber",
  "WeChat Work": "企业微信",
  "DingTalk": "钉钉",
  "Feishu": "飞书",
  "Tencent Meeting": "腾讯会议",
  "VooV Meeting": "腾讯会议国际版",
  "Coinbase": "Coinbase",
  "Binance": "币安",
  "Kraken": "Kraken",
  "Robinhood": "Robinhood",
  "E*TRADE": "E*TRADE",
  "Charles Schwab": "嘉信理财",
  "Fidelity": "富达",
  "Wise": "Wise",
  "Revolut": "Revolut",
  "N26": "N26",
  "Etsy": "Etsy",
  "AliExpress": "速卖通",
  "Wish": "Wish",
  "Overstock": "Overstock",
  "Wayfair": "Wayfair",
  "Target": "Target",
  "Walmart": "沃尔玛",
  "Costco": "好市多",
  "Best Buy": "百思买",
  "Newegg": "新蛋",
  "BBC": "BBC",
  "CNN": "CNN",
  "Reuters": "路透社",
  "AP News": "美联社",
  "New York Times": "纽约时报",
  "Wall Street Journal": "华尔街日报",
  "The Guardian": "卫报",
  "The Economist": "经济学人",
  "Forbes": "福布斯",
  "TechCrunch": "TechCrunch",
  "The Verge": "The Verge",
  "Wired": "连线",
  "Ars Technica": "Ars Technica",
  "Engadget": "Engadget",
  "Mashable": "Mashable",
  "BuzzFeed": "BuzzFeed",
  "VICE": "VICE",
  "1Password": "1Password",
  "LastPass": "LastPass",
  "Bitwarden": "Bitwarden",
  "NordVPN": "NordVPN",
  "ExpressVPN": "ExpressVPN",
  "Surfshark": "Surfshark",
  "Grammarly": "Grammarly",
  "DeepL": "DeepL",
  "Google Translate": "Google 翻译",
  "Wolfram Alpha": "Wolfram Alpha",
  "Calculator.net": "Calculator.net",
  "Convertio": "Convertio",
  "SmallPDF": "SmallPDF",
  "WeTransfer": "WeTransfer",
  "MEGA": "MEGA",
  "Box": "Box",
  "Zhihu Live": "知乎Live",
  "Douyin Live": "抖音直播",
  "Kuaishou Live": "快手直播",
  "Huya": "虎牙直播",
  "Douyu": "斗鱼直播",
  "YY": "YY语音",
  "Miaopai": "秒拍",
  "JD Global": "京东全球",
  "Tumblr": "Tumblr",
  "Zalando": "Zalando",
  "ASOS": "ASOS",
  "H&M": "H&M",
  "Zara": "Zara",
  "Disney+": "Disney+",
  "Hulu": "Hulu",
  "Prime Video": "Prime Video",
  "HBO Max": "HBO Max",
  "Paramount+": "Paramount+",
  "Peacock": "Peacock",
  "Apple TV+": "Apple TV+",
  "Crunchyroll": "Crunchyroll",
  "Tidal": "Tidal",
  "Amazon Music": "Amazon Music",
  "YouTube Music": "YouTube Music",
  "Terraform": "Terraform",
  "Ansible": "Ansible",
  "Adobe Creative": "Adobe创意",
  "Adobe XD": "Adobe XD",
  "Principle": "Principle",
  "ProtoPie": "ProtoPie",
  "Monday.com": "Monday.com",
  "ClickUp": "ClickUp",
  "Basecamp": "Basecamp",
  "edX": "edX",
  "Skillshare": "Skillshare",
  "MasterClass": "MasterClass",
  "LinkedIn Learning": "LinkedIn学习",
  "Pluralsight": "Pluralsight",
  "Steam": "Steam",
  "Epic Games": "Epic Games",
  "Ubisoft": "育碧",
  "EA Games": "EA游戏",
  "Activision": "动视",
  "Roblox": "Roblox",
  "Booking.com": "Booking.com",
  "Kayak": "Kayak",
  "Skyscanner": "Skyscanner",
  "TripAdvisor": "猫途鹰",
  "Uber": "Uber",
  "Lyft": "Lyft",
  "MyFitnessPal": "MyFitnessPal",
  "Strava": "Strava",
  "Fitbit": "Fitbit",
  "Apple Health": "Apple健康",
  "Calm": "Calm",
  "Headspace": "Headspace",
  "Peloton": "Peloton",
  "Nike Training": "Nike训练"
}
